name: iot_home
description: A little iot-core project using MQTT and my beagle bone
version: 2.0.1
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/iot-home

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  mqtt_client: '^8.1.0'
  just_jwt:
    git: https://github.com/shamblett/JustJWT.git
  mraa: '^1.3.0'
  args: '^1.5.0'
  intl: '^0.17.0-nullsafety.2'
  grove: '^2.0.0'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  pana: '^0.14.10'

