name: iot_home
description: A little iot-core project using MQTT and some simple sensors to provide data.
version: 3.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/iot-home

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mqtt_client: '^9.0.0'
  just_jwt:
    git: https://github.com/shamblett/JustJWT.git
  mraa: '^2.0.0'
  args: '^2.0.0'
  intl: '^0.17.0'
  grove: '^3.0.0'

dev_dependencies:
  test: '^1.16.8'


