name: iot_home
description: A little iot-core project using MQTT and some simple sensors to provide data.
version: 4.0.0
repository: https://github.com/shamblett/iot-home

environment:
  sdk: '>=3.0.0 <4.0.0'

publish_to: 'none'

dependencies:
  mqtt_client: '^10.0.0'
  just_jwt:
    git: https://github.com/shamblett/JustJWT.git
  mraa: '^4.0.0'
  args: '^2.4.1'
  intl: '^0.18.1'
  grove: '^4.0.0'
  path: '^1.8.3'
  typed_data: '^1.3.2'

dev_dependencies:
  test: '^1.16.8'
  lints: '^2.0.0'


