name: iot_home
description: A little iot-core project using MQTT and some simple sensors to provide data.
version: 3.0.1
repository: https://github.com/shamblett/iot-home

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  mqtt_client: '^9.0.0'
  just_jwt:
    git: https://github.com/shamblett/JustJWT.git
  mraa: '^2.0.0'
  args: '^2.0.0'
  intl: '^0.18.0'
  grove: '^3.0.0'
  path: '^1.8.3'
  typed_data: '^1.3.1'

dev_dependencies:
  test: '^1.16.8'
  lints: '^2.0.0'


